name: CI Checks

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/**'

jobs:
  checks:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Tests with coverage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :statistics:koverVerifyDebug
          
      - name: Create coverage-data directory and copy contents
        run: |
          mkdir -p .qodana/code-coverage
          cp -R statistics/build/kover/bin-reports/* .qodana/code-coverage/
      
      - name: Archive coverage data
        uses: actions/upload-artifact@v2
        with:
          name: gradle-coverage-data.zip
          path: .qodana/code-coverage
    
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  

