name: Push checks
permissions:
  contents: write
on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
jobs:
  checks:
    name: Qodana
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create coverage-data directory and copy contents
        run: |
          mkdir -p .qodana/code-coverage
          rm -rf .qodana/code-coverage/**

      - name: Tests with coverage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: koverBinaryReportDebug copyCoverage

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: -l,jetbrains/qodana-android:2024.1-eap